# Generated by Django 5.0.6 on 2024-05-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_remove_projects_created_by_alter_tasks_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(),
        ),
    ]
